package d17;

public class ExceptionStudy {
	public void A() {
		// 문제 1. 
//		try {
//		} catch(Throwable t) {	
//		} catch(Exception e) {}
		
		// 문제 2. RuntimeException 
		// 컴파일 단계에서 exception 처리하지 말고 
		// runtime에서 try catch로 처리해라.
		
		// 문제 3. try ~ with resource
		// try( ) => AutoCloseable만 들어간다. 변수가 final이 된다.
		// with 구문? 객체의 범위를 조정할 때 쓴다. 
		
	}
}
